# Generated by Django 2.2.10 on 2021-08-12 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('time', models.CharField(default='April 6, 2020 18:30:00', max_length=40)),
                ('current_level', models.IntegerField(default=1)),
                ('total_level', models.IntegerField(default=1)),
                ('freeze_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('next_sit', models.IntegerField()),
                ('end', models.BooleanField(default=False)),
                ('message', models.CharField(default='na', max_length=200)),
                ('image', models.ImageField(default='https://source.unsplash.com/random', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('current_sitn', models.IntegerField(default=1)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('level', models.IntegerField(default=1)),
                ('completed_or_dead', models.BooleanField(default=False)),
                ('visited_nodes', models.CharField(blank=True, default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_no', models.IntegerField(unique=True)),
                ('image', models.ImageField(default='images/level1.jpg', upload_to='images')),
                ('level', models.IntegerField(default=1)),
                ('sub', models.BooleanField(default=False)),
                ('next_sitn', models.IntegerField(default=1, help_text='Next situation number')),
                ('ans', models.CharField(default='NA', help_text='Answer for the subjective question', max_length=100)),
                ('text', models.TextField()),
                ('options', models.ManyToManyField(blank=True, to='mindapp.option')),
            ],
        ),
        migrations.CreateModel(
            name='SituationTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindapp.Player')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindapp.Situation')),
            ],
        ),
    ]
