# Generated by Django 2.1.5 on 2020-03-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('next_sit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Situations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_no', models.IntegerField()),
                ('text', models.TextField()),
                ('option1', models.ManyToManyField(to='mindapp.option')),
            ],
        ),
    ]
