# Generated by Django 2.1.5 on 2020-03-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0002_option_situations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situations',
            name='option1',
        ),
    ]
