# Generated by Django 2.1.5 on 2020-03-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0003_remove_situations_option1'),
    ]

    operations = [
        migrations.AddField(
            model_name='situations',
            name='image',
            field=models.ImageField(default='images/level1.jpg', upload_to='images'),
        ),
    ]
