# Generated by Django 2.1.5 on 2020-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0004_situations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='situations',
            name='option_1',
            field=models.ManyToManyField(related_name='option1', to='mindapp.option'),
        ),
        migrations.AddField(
            model_name='situations',
            name='option_2',
            field=models.ManyToManyField(related_name='option2', to='mindapp.option'),
        ),
    ]
