# Generated by Django 2.1.5 on 2020-03-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0005_auto_20200329_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situations',
            name='option_2',
            field=models.ManyToManyField(related_name='option3', to='mindapp.option'),
        ),
    ]
