# Generated by Django 2.1.5 on 2020-03-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0006_auto_20200329_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situations',
            name='option_1',
        ),
        migrations.AddField(
            model_name='situations',
            name='option_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='mindapp.option'),
        ),
    ]
