# Generated by Django 2.1.5 on 2020-03-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0008_auto_20200329_0319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Situations',
            new_name='Situation',
        ),
    ]
