# Generated by Django 2.1.5 on 2020-03-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0012_option_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='situation_no',
            field=models.IntegerField(unique=True),
        ),
    ]
