# Generated by Django 2.1.4 on 2020-03-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0013_auto_20200329_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='next_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situation',
            name='sub',
            field=models.BooleanField(default=False),
        ),
    ]
