# Generated by Django 2.1.5 on 2020-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0016_auto_20200331_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='ans',
            field=models.CharField(default='NA', help_text='Answer for the subjective question', max_length=100),
        ),
        migrations.AlterField(
            model_name='situation',
            name='next_sitn',
            field=models.IntegerField(default=1, help_text='Next situation number'),
        ),
    ]
