# Generated by Django 2.1.5 on 2020-03-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0018_option_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindapp.Player')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindapp.Situation')),
            ],
        ),
    ]
