# Generated by Django 2.1.5 on 2020-03-31 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0019_situationtimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationtimer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindapp.Player'),
        ),
        migrations.AlterField(
            model_name='situationtimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
