# Generated by Django 2.2.10 on 2020-04-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0030_auto_20200402_0032'),
        ('mindapp', '0041_auto_20200404_1248'),
    ]

    operations = [
    ]
