# Generated by Django 2.2.10 on 2020-04-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0042_merge_20200404_1312'),
        ('mindapp', '0042_auto_20200404_2017'),
    ]

    operations = [
    ]
