# Generated by Django 2.2.10 on 2021-08-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0056_auto_20210807_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='option_3',
        ),
        migrations.AddField(
            model_name='situation',
            name='options',
            field=models.ManyToManyField(blank=True, to='mindapp.option'),
        ),
        migrations.AlterField(
            model_name='situationtimer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindapp.Player'),
        ),
    ]
